services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: financesK-frontend-prod
    ports:
      - "3031:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - financesk-net

networks:
  financesk-net:
    driver: bridge
