services:
  # Frontend Development (Backend Real)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: financesk-frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:8080
    networks:
      - microservices-network
    depends_on:
      - nginx-real
    restart: unless-stopped

  # Nginx para Backend Real
  nginx-real:
    image: nginx:alpine
    container_name: financesk-nginx-real
    volumes:
      - ./nginx-real-backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-network
    restart: unless-stopped

  # Frontend Development (Backend Mock)
  frontend-dev-mock:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: financesk-frontend-dev-mock
    ports:
      - "4201:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8081
    networks:
      - financesk-mock-network
    depends_on:
      - backend-mock
    restart: unless-stopped
    profiles:
      - mock

  # Mock Backend
  backend-mock:
    image: nginx:alpine
    container_name: financesk-backend-mock
    ports:
      - "8080:80"
    volumes:
      - ./mock-backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - financesk-mock-network
    restart: unless-stopped
    profiles:
      - mock

  # Frontend Production (Backend Real)
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: financesk-frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network
    restart: unless-stopped
    profiles:
      - production

  # Frontend Production (Backend Mock)
  frontend-prod-mock:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-mock
    container_name: financesk-frontend-prod-mock
    ports:
      - "81:80"
    volumes:
      - ./mock-data:/usr/share/nginx/html/api
    networks:
      - financesk-mock-network
    restart: unless-stopped
    profiles:
      - production-mock

networks:
  microservices-network:
    external: true
    name: microservices-network
  financesk-mock-network:
    external: true
    name: financesk-mock-network

volumes:
  node_modules:
